name: delegation_verifier

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.5
  settings_yaml: ^3.4.0
  hex: ^0.2.0
  logging: ^1.0.2
  znn_sdk_dart:
    git:
      url: https://github.com/zenon-network/znn_sdk_dart.git
      ref: master